wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.10.4
    start_time: 1656050806
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 80
      3:
      - 7
      - 13
      - 23
      4: 3.10.4
      5: 0.12.19
      8:
      - 1
      - 5
